# Generated by Django 2.2.4 on 2019-12-15 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.FloatField()),
                ('item_discounted_price', models.FloatField(blank=True, null=True)),
                ('item_description', models.TextField()),
                ('item_category', models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sports Wear'), ('OW', 'Out Wear')], default='S', max_length=2)),
                ('item_label', models.CharField(choices=[('P', 'primary'), ('S', 'success'), ('D', 'danger')], default='P', max_length=1)),
                ('item_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('item_image', models.CharField(default='http://leeford.in/wp-content/uploads/2017/09/image-not-found.jpg', max_length=500)),
                ('slug', models.SlugField(default='test-product')),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
            options={
                'db_table': 'Order Item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField()),
                ('is_ordered', models.BooleanField(default=False)),
                ('order_items', models.ManyToManyField(to='core.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
