# Generated by Django 2.2.4 on 2019-12-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
