# Generated by Django 2.2.4 on 2019-12-24 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_orderitem_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=500)),
                ('shipping_same_as_billing', models.BooleanField(default=False)),
                ('save_info', models.BooleanField(default=False)),
                ('payment_info', models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
