# Generated by Django 2.2.4 on 2019-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginformation',
            name='pin_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
